export const StoryTitleQuestions = {
    YourStory: [
        "What's your story?",
        "Why do you believe in Christianity?",
        "Why are you a Christian?",
        "What are the key moments of your spiritual journey?",
        "How has your faith shaped your life?",
        "What does being a Christian mean to you?"
    ],
    GodsStory: [
        "What is Christianity?",
        "What is actually the Gospel?",
        "What does the Bible actually say?",
        "What do you actually believe about God?",
        "What's the point of Christianity?",
        "Why should I be a Christian?"
    ]
};



// Each day, users receive a new, easy-to-ask question. These questions are designed
// to natually lead to deeper conversations, which could segue into faith-sharing moments.
export const PromptQuestions = [
    "Do you have any spiritual beliefs?",
    "How can I pray for you?",
    "Are you a religious person?",
    "Do you have a church that you attend?",
    "Did you grow up in church? What were you taught about God growing up? Do you still believe that?",
    "What do you think the solution is to (insert recent troubling news event)?",
    "Can I share my story with you briefly?",
    "Can I tell you about the best thing that ever happened to me?",
    "What do you think it takes to go to heaven?",
    "Who has been a mentor or role model that made a big impact on your life?",
    "What's one of the best pieces of advice you've ever received?",
    "If you could spend a day with anyone, living or dead, who would it be?",
    "What's something that gives you hope when life gets tough?",
    "What's a challenge you've overcome that taught you something important?",
    "What's one thing you're thankful for this week?",
    "What do you think the purpose of life is?",
    "What's the most meaningful gift you've ever received?",
    "Who is someone you admire for the way they live their life?",
    "What's a book, movie, or story that's really inspired you?",
    "What do you think happens after we die?",
    "What's something you do to recharge or find peace?",
    "Who is someone you look up to for their character?",
    "What's a tradition or habit that's important to you?",
    "What's a time in your life when you experienced unexpected joy?",
    "If you could change one thing in the world, what would it be?",
    "Who is someone who helped you get through a difficult time?",
    "What do you think makes a person truly happy?",
    "What are you passionate about?",
    "What's one thing you'd like to do more of in your life?",
    "What would you want to be remembered for?",
    "What do you think makes a person truly successful?",
    "What's a lesson you've learned from failure?",
    "If you had unlimited resources, what problem would you solve in the world?",
    "What's something you've done that you're really proud of?",
    "What's a habit that's made a positive impact in your life?",
    "What's a moment in your life that changed everything?",
    "What do you turn to when you need comfort or strength?",
    "What's the most important thing you want to achieve in your life?",
    "What's a book or quote that's really influenced you?",
    "What's a quality you admire in other people?",
    "What do you think is the most importat thing in a person's character?",
    "What's something that's given you a sense of purpose?",
    "What's something you feel deeply grateful for?",
    "What's something you've been learning or growing in lately?",
    "What do you think makes life meaningful?",
    "If you could give advice to your younger self, what would it be?",
    "What's something you want to invest more time in?"
]

export const PromptQuestions2 = {
    church: [
        "Hey, want to check out my church this Sunday?",
        "Do you have any background in faith?",
        "What do you look for in a church community?",
        "Have you ever been to a church service before?",
        "What does a supportive community look like to you?",
        "Have you ever thought about exploring different faith communities?",
        "How important is spiritual growth to you?",
        "What would make you interested in visiting a church?",
        "Do you have any particular beliefs or values that you hold close?"
    ],
    spiritual: [
        "Have you had any spiritual experiences lately?",
        "What do you think about Jesus?",
        "If you were in front of God right now, what one question would you ask him?",
        "Do you have any questions about Christianity?",
        "How do you feel about the idea of a higher power?",
        "What's your perspective on faith and spirituality?",
        "What do you think happens after we die?",
        "Have you ever felt like you've encountered something beyond the physical world?",
        "What role does prayer or meditation play in your life, if any?",
        "What are your thoughts on the concept of eternal life?",
        "Do you believe in miracles?"
    ],
    workCareer: [
        "How do your beliefs impact your work ethic?",
        "Have you ever felt a conflict between your job and your values?",
        "What role does faith play in your career decisions?",
    ],
    relationships: [
        "How important is faith in your relationships?",
        "Do you and your partner share the same spiritual beliefs?",
        "How do you navigate spiritual differences in your relationships?",
    ],
    communityService: [
        "Do you participate in any community service or volunteering?",
        "How do you feel about giving back to the community?",
        "What role does service play in your life?",
    ],
    healthWellbeing: [
        "How do you balance physical health with spiritual well-being?",
        "Have you ever experienced healing through prayer?",
        "What practices do you follow to maintain your mental and spiritual health?",
    ],
    general: [
        "What's been going on in your life?",
        "How have you been feeling lately?",
        "What's something exciting happening in your life right now?",
        "What are some goals you're currently working towards?",
        "What have you been passionate about lately?",
        "Is there anything you're looking forward to in the next few weeks?",
        "How do you usually spend your weekend?",
        "What's something new that you've picked up recently?",
        "Have you picked up any new hobbies or interests?",
        "What's something you're grateful for today?",
        "What's been challenging you lately?",
        "How do you usually unwind after a long day?",
        "What has inspired you recently?",
        "What's a book or movie that really impacted you?",
        "How do you stay motivated when things get tough?",
        "What's something you've learned about yourself this year?",
        "What are some places you'd like to travel to someday?",
        "How do you like to spend your time when you're alone?"
    ],
};

export const ActivityNoteOptions = [
    "You are not alone; I'm praying for you.",
    "Lifting you up in prayer.",
    "May you find peace and strength.",
    "May you feel God's presence.",
    "Praying for comfort and guidance.",
    "You are in my thoughts and prayers.",
    "May your faith be strengthened.",
    "Sending prayers for your well-being.",
    "Believing for a breakthrough.",
    "Praying for wisdom and clarity.",
    "Praying for healing and peace.",
    "Trusting in God's plan for you.",
    "May you find hope and courage.",
    "Asking God to bless you today.",
    "May you experience God's peace.",
    "Custom"
];

export const PracticeTestimonyQuestions = [
    "Who has been an important person in your faith journey?",
    "What was your upbringing like?",
    "What were your parent(s)' views on religion?",
    "What is one aspect of how you have changed since following Jesus?",
    "What gives you hope for the future?",
    "Have you ever been challenged in your faith? What was that like?",
    "How did your childhood shape your view of faith?",
    "What was life like for you before you became a Christian?",
    "Can you describe the moment you first truly understood who Jesus is?",
    "How has your relationship with Jesus changed your daily life?",
    "What has been a highlight in your walk with Christ?",
    "Can you share a low moment in your faith journey and how you overcame it?",
    "Where do you see God working in your life right now?",
    "How did your family influence your faith journey?",
    "What was the hardest thing for you to give up when you chose to follow Jesus?",
    "Was there a specific event or person that led you to give your life to Christ?",
    "How has your faith impacted your identity and sense of purpose?",
    "What doubts or questions did you struggle with before coming to Christ?",
    "Have you ever felt God’s presence in a tough situation? How?",
    "How has your faith helped you in times of grief or loss?",
    "How do you find peace in the midst of life’s struggles?",
    "In what ways have you seen transformation in your character since following Jesus?",
    "How do you handle doubts about your faith when they arise?",
    "What role does your community play in supporting your faith?",
    "How has God’s love brought healing to your emotional wounds?",
    "Has your relationship with God changed how you see your work or career?",
    "How has following Jesus affected your relationships with friends or family?",
    "What challenges have you faced as a Christian in today's culture?",
    "Can you share a time when your faith felt especially strong or weak?",
    "How has your faith helped you navigate major life transitions?",
    "What gives you the most joy in your relationship with God?",
    "Can you recall a time when you had to forgive someone? How did your faith help?",
    "How has your prayer life evolved since you began following Christ?",
    "How do you stay focused on your faith in your busy daily life?",
    "What role does worship play in your spiritual life?",
    "How has your faith given you peace in uncertain times?",
    "How has God guided you through moments of indecision or confusion?",
    "How has your faith helped you through financial struggles?",
    "How has your understanding of love changed since following Jesus?",
    "How do you see God working in the lives of people around you?",
    "How has being part of a church or small group strengthened your faith?",
    "How do you see God’s purpose for your life unfolding now?",
    "Can you describe a time when you experienced God’s faithfulness?",
    "How do you share your faith at work or school?",
    "What role does music or worship play in connecting you to God?",
    "What Scripture has deeply influenced your life?",
    "What is one passage in Scripture that means a lot to you?",
    "What was a favorite Bible verse you had growing up?",
    "How has your faith helped you overcome fears or anxieties?",
    "Can you share a moment when you felt God calling you to serve others?",
    "How has your relationship with God influenced your understanding of forgiveness?",
    "What spiritual practices help you stay grounded in your faith?",
    "How has your faith helped you find hope in the midst of suffering?",
    "Have you ever shared your testimony with someone? How did it impact them?",
    "What part of your story do you think resonates most with others?",
];
